name: publish snapshot

on:
  push:
    branches:
      - 'master'
      - 'snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:

  upload:
    name: Upload
    uses: ./.github/workflows/build.yml
    with:
      channel: snapshot
      gradleArgs: -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }}
