name: publish snapshot

on:
  push:
    branches:
      - 'master'
      - 'snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:

  upload:
    name: Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Publish Linux to Maven Local
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: ./gradlew publishLinuxPublicationToMavenLocal
      - name: Publish MacOS to Maven Local
        if: matrix.os == 'macOS-latest'
        shell: bash
        run: ./gradlew publishToMavenLocal
      - name: Copy artifact files
        run: |
          mkdir -p maven-local/snapshot
          cp -r ~/.m2/repository/* maven-local/snapshot
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snapshot
          path: |
            maven-local
            !maven-local/**/maven-metadata-local.xml