name: Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'
  push:
    branches:
      - '!master'
      - '!snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'

jobs:
  check:
    name: Check
    uses: ./.github/workflows/build.yml
